# Семинар 1

## План ноутбука

1. Установка `PyTorch`
1. Введение в `PyTorch`

## Установка `PyTorch`

Мы будем использовать библиотеку для глубинного обучения `PyTorch`, ее можно не устанавливать, можно пользоваться сайтами [Kaggle](kaggle.com) и [Google Colab](colab.research.google.com/) для обучения в облаке. 

Чтобы установить `PyTorch` локально себе на компьютер нужно ответить на два вопроса - какая у вас операционная система и есть ли у вас дискретная видеокарта (GPU) и если есть, то какого производителя. В зависимости от ваших ответов мы получаем три варианта по операционной системе - Linux, Mac и Windows; три варианта по дискретной видеокарте - нет видеокарты (доступен только центральный процессор CPU), есть видеокарта от Nvidia или есть видеокарта от AMD (это производитель именно чипа, конечный вендор может быть другой, например, ASUS, MSI, Palit). Работа с PyTorch с видеокартой от AMD это экзотика, которая выходит за рамки нашего курса, поэтому рассмотрим только варианты *нет видеокарты*/*есть видеокарта от Nvidia*.


Выберите на [сайте](https://pytorch.org/get-started/locally/) подходящие вам варианты операционной системы/видеокарты и скопируйте команду для установки. Разберем подробно самые популярные варианты установки:

### Установка в Linux ([поддерживаемые дистрибутивы](https://pytorch.org/get-started/locally/#supported-linux-distributions))

На линуксе будет работать поддержка `PyTorch` в любой конфигурации, что у вас нет видеокарты, что есть от Nvidia, что от AMD. 

Пререквизит для работы с видеокартой от Nvidia - нужно поставить CUDA, это инструмент от компании Nvidia, который позволяет ускорять вычисления на их же ГПУ. Чтобы поставить себе на машину все правильно воспользуйтесь этим [гайдом](https://docs.nvidia.com/cuda/cuda-installation-guide-linux/index.html) от Nvidia.

 - **pip**

`pip3 install torch torchvision torchaudio --extra-index-url https://download.pytorch.org/whl/cpu` для тех, у кого нет видеокарты.

`pip3 install torch torchvision torchaudio --extra-index-url https://download.pytorch.org/whl/cu118` для тех, у кого есть видеокарта (либо другой `--extra-index-url`, смотрите на сайте PyTorch, в зависимости от версии CUDA).

 - **conda**

`conda install pytorch torchvision torchaudio cpuonly -c pytorch` для тех, у кого нет видеокарты.

`conda install pytorch torchvision torchaudio cudatoolkit=11.8 -c pytorch -c conda-forge` для тех, у кого есть видеокарта (либо немного другая команда, в зависимости от версии CUDA).

### Установка в Windows

На винде будет работать поддержка `PyTorch` только для видеокарт от Nvidia и без видеокарт вообще. 

Пререквизит для работы с видеокартой от Nvidia - нужно поставить CUDA, это инструмент от компании Nvidia, который позволяет ускорять вычисления на их же ГПУ. Чтобы поставить себе на машину все правильно воспользуйтесь этим [гайдом](https://docs.nvidia.com/cuda/cuda-installation-guide-microsoft-windows/index.html) от Nvidia.

 - **pip**

`pip3 install torch torchvision torchaudio --extra-index-url https://download.pytorch.org/whl/cpu` для тех, у кого нет видеокарты.

`pip3 install torch torchvision torchaudio --extra-index-url https://download.pytorch.org/whl/cu118` для тех, у кого есть видеокарта (либо другой `--extra-index-url`, смотрите на сайте PyTorch, в зависимости от версии CUDA).

 - **conda**

`conda install pytorch torchvision torchaudio cpuonly -c pytorch` для тех, у кого нет видеокарты.

`conda install pytorch torchvision torchaudio cudatoolkit=11.8 -c pytorch -c conda-forge` для тех, у кого есть видеокарта (либо немного другая команда, в зависимости от версии CUDA).



### Установка на Mac

На маках есть поддержка `PyTorch` как на CPU, так и на GPU, но только для Apple Silicon, то есть на чипах M1, M2 и так далее.

При этом поддержка ускорения с помощью GPU есть только для версий макоси выше 12.3: MPS acceleration is available on MacOS 12.3+

 - **pip**

`pip3 install torch torchvision torchaudio`

 - **conda**

`conda install pytorch::pytorch torchvision torchaudio -c pytorch`

##  IDE vs Jupyter

Использовать можно как юпитер тетрадки, так и IDE для написания кода. 

Важно понимать, что при использвании тетрадок может нарушаться логика кода. Всегда проверяйте, что тетрадка исполняется от начала и до конца, выдавая тот же результат.

Мой выбор для повседневной работы - IDE со скриптами. Лучше разделять код для описания моделей и обучения на разные файлы.

В качестве IDE я рекомендую PyCharm.

## PyTorch и тензоры

Тензор с размерностью 1 - это просто вектор, список чисел.

Тензор с размерностью 2 - это просто матрица, то есть список списков чисел.

Тензор с размерностью 3 и больше - это тензор, то есть список списков списков ... чисел.

![](misc/meme.png)

## Torch

https://www.dataschool.io/jupyter-notebook-keyboard-shortcuts/

In [62]:
import torch  # <Ctrl> / <Shift> + <Return>

In [3]:
simple_var = 2

In [4]:
simple_var

2

## Getting help in Jupyter

In [2]:
torch.sq  # <Tab>

AttributeError: module 'torch' has no attribute 'sq'

In [63]:
# What about all `*Tensor`s?
# Press <esc> to get out of help
torch.*Tensor?

In [6]:
torch.nn.Module()  # <Shift>+<Tab>

Module()

In [11]:
# Annotate your functions / classes!
torch.nn.Module?

In [12]:
torch.nn.Module??

## Dropping to Bash: magic!

In [8]:
# List all the files in the current directory
!ls -lh

total 40K
drwxrwxr-x 3 administrator administrator 4.0K Jan 17 18:43 misc
-rw-rw-r-- 1 administrator administrator  33K Jan 17 20:01 Seminar-1.ipynb


In [9]:
%%bash
# List all the files but with cleaner outputs for readability
for f in $(ls *.*); do
    echo $(wc -l $f)
done

1445 Seminar-1.ipynb


In [10]:
# Getting some general help
%magic

## Torch!

In [14]:
# Generate a tensor of size 2x3x4
t = torch.Tensor(2, 3, 4)
type(t)

torch.Tensor

In [19]:
t

tensor([[[-4.8420e+01,  4.5768e-41,  1.5773e-34,  0.0000e+00],
         [-1.5148e+18,  4.5766e-41, -1.5147e+18,  4.5766e-41],
         [-1.5152e+18,  4.5766e-41, -1.5153e+18,  4.5766e-41]],

        [[-1.5149e+18,  4.5766e-41, -1.5146e+18,  4.5766e-41],
         [-1.5150e+18,  4.5766e-41, -1.5146e+18,  4.5766e-41],
         [-1.5149e+18,  4.5766e-41, -1.5145e+18,  4.5766e-41]]])

In [16]:
# Get the size of the tensor
t.size()

torch.Size([2, 3, 4])

In [18]:
t[:, :, 1]

tensor([[4.5768e-41, 4.5766e-41, 4.5766e-41],
        [4.5766e-41, 4.5766e-41, 4.5766e-41]])

In [20]:
# t.size() is a classic tuple =>
print('t size:', ' \u00D7 '.join(map(str, t.size())))

t size: 2 × 3 × 4


In [21]:
# prints dimensional space and sub-dimensions
print(f'point in a {t.numel()} dimensional space')
print(f'organised in {t.dim()} sub-dimensions')

point in a 24 dimensional space
organised in 3 sub-dimensions


In [35]:
torch.random(10)

AttributeError: type object 'Tensor' has no attribute 'random'

In [33]:
# Mind the underscore!
# Any operation that mutates a tensor in-place is post-fixed with an _.
# For example: x.copy_(y), x.t_(), x.random_(n) will change x.
t = torch.Tensor(2, 3, 4)

t.random_(10)

tensor([[[6., 8., 9., 4.],
         [0., 2., 9., 0.],
         [4., 1., 1., 7.]],

        [[1., 5., 7., 9.],
         [4., 5., 3., 0.],
         [1., 0., 7., 1.]]])

In [36]:
t

tensor([[[6., 8., 9., 4.],
         [0., 2., 9., 0.],
         [4., 1., 1., 7.]],

        [[1., 5., 7., 9.],
         [4., 5., 3., 0.],
         [1., 0., 7., 1.]]])

In [37]:
# This resizes the tensor permanently 
r = torch.Tensor(t)
r.resize_(3, 8)
r

tensor([[6., 8., 9., 4., 0., 2., 9., 0.],
        [4., 1., 1., 7., 1., 5., 7., 9.],
        [4., 5., 3., 0., 1., 0., 7., 1.]])

In [38]:
# As you can see zero_ would replace r with 0's which was originally filled with integers
r.zero_()

tensor([[0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.]])

In [39]:
torch.zeros(3, 8)

tensor([[0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.]])

In [ ]:
[1, 2]

In [26]:
# This *is* important, sigh...
s = r.clone()

In [27]:
# In-place fill of 1's
s.fill_(1)
s

tensor([[1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.]])

In [28]:
# Because we cloned r, even though we did an in-place operation, this doesn't affect r
r

tensor([[0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.]])

## Vectors (1D Tensors)

In [41]:
# Creates a 1D tensor of integers 1 to 4
v = torch.Tensor([1, 2, 3, 4])
v

tensor([1., 2., 3., 4.])

In [42]:
# Print number of dimensions (1D) and size of tensor
print(f'dim: {v.dim()}, size: {v.size()[0]}')

dim: 1, size: 4


In [46]:
w = torch.Tensor([1, 0, 2, 0])
w

tensor([1., 0., 2., 0.])

In [47]:
# Element-wise multiplication
v * w

tensor([1., 0., 6., 0.])

In [48]:
# Scalar product: 1*1 + 2*0 + 3*2 + 4*0
v @ w

tensor(7.)

In [38]:
# In-place replacement of random number from 0 to 10
x = torch.Tensor(5).random_(10)
x

tensor([4., 2., 4., 4., 5.])

In [39]:
print(f'first: {x[0]}, last: {x[-1]}')

first: 4.0, last: 5.0


In [40]:
# Extract sub-Tensor [from:to)
x[1:2 + 1]

tensor([2., 4.])

In [ ]:
v

In [41]:
# Create a tensor with integers ranging from 1 to 5, excluding 5
v = torch.arange(1, 4 + 1)
v

tensor([1, 2, 3, 4])

In [42]:
# Square all elements in the tensor
print(v.pow(2), v)

tensor([ 1,  4,  9, 16]) tensor([1, 2, 3, 4])


## Matrices (2D Tensors)

In [49]:
import numpy as np
# Create a 2x4 tensor
m = torch.Tensor(np.array([[2, 5, 3, 7],
                  [4, 2, 1, 9]]))
m

tensor([[2., 5., 3., 7.],
        [4., 2., 1., 9.]])

In [50]:
m.dim()

2

In [51]:
print(m.size(0), m.size(1), m.size(), sep=' -- ')

2 -- 4 -- torch.Size([2, 4])


In [52]:
# Returns the total number of elements, hence num-el (number of elements)
m.numel()

8

In [54]:
# Indexing row 0, column 2 (0-indexed)
m[0][2]

tensor(3.)

In [55]:
# Indexing row 0, column 2 (0-indexed)
m[0, 2]

tensor(3.)

In [56]:
# Indexing column 1, all rows (returns size 2)
m[:, 1]

tensor([5., 2.])

In [49]:
# Indexing column 1, all rows (returns size 2x1)
m[:, [1]]

tensor([[5.],
        [2.]])

In [51]:
# Indexes row 0, all columns (returns 1x4)
m[[0], :]

tensor([[2., 5., 3., 7.]])

In [52]:
# Indexes row 0, all columns (returns size 4)
m[0, :]

tensor([2., 5., 3., 7.])

In [53]:
# Create tensor of numbers from 1 to 5 (excluding 5)
v = torch.arange(1., 4 + 1)
v

tensor([1., 2., 3., 4.])

In [54]:
m

tensor([[2., 5., 3., 7.],
        [4., 2., 1., 9.]])

In [55]:
# Scalar product
m @ v

tensor([49., 47.])

In [56]:
# Calculated by 1*2 + 2*5 + 3*3 + 4*7
m[[0], :] @ v

tensor([49.])

In [57]:
# Calculated by 
m[[1], :] @ v

tensor([47.])

In [58]:
# Add a random tensor of size 2x4 to m
m + torch.rand(2, 4)

tensor([[2.5393, 5.9965, 3.8281, 7.7213],
        [4.1677, 2.2628, 1.9187, 9.8275]])

In [59]:
# Subtract a random tensor of size 2x4 to m
m - torch.rand(2, 4)

tensor([[1.6716, 4.2886, 2.9497, 6.9646],
        [3.7375, 1.7958, 0.3524, 8.5174]])

In [60]:
# Multiply a random tensor of size 2x4 to m
m * torch.rand(2, 4)

tensor([[1.5119, 3.8195, 1.6333, 3.3801],
        [1.6799, 1.8496, 0.8404, 0.2086]])

In [61]:
# Divide m by a random tensor of size 2x4
m / torch.rand(2, 4)

tensor([[  2.5355,   6.3659,   6.5696,   7.3787],
        [ 12.7114,   3.8403,   1.8969, 219.4235]])

In [62]:
m.size()

torch.Size([2, 4])

In [63]:
# Transpose tensor m, which is essentially 2x4 to 4x2
m.t()

tensor([[2., 4.],
        [5., 2.],
        [3., 1.],
        [7., 9.]])

In [64]:
# Same as
m.transpose(0, 1)

tensor([[2., 4.],
        [5., 2.],
        [3., 1.],
        [7., 9.]])

## Constructors

In [67]:
# Create tensor from 3 to 8, with each having a space of 1
torch.arange(3., 8 + 1, dtype=torch.float32)

tensor([3., 4., 5., 6., 7., 8.])

In [68]:
# Create tensor from 5.7 to -2.1 with each having a space of -3
torch.arange(5.7, -2.1, -3)

tensor([ 5.7000,  2.7000, -0.3000])

In [69]:
# returns a 1D tensor of steps equally spaced points between start=3, end=8 and steps=20
torch.linspace(3, 8, 20).view(1, -1)

tensor([[3.0000, 3.2632, 3.5263, 3.7895, 4.0526, 4.3158, 4.5789, 4.8421, 5.1053,
         5.3684, 5.6316, 5.8947, 6.1579, 6.4211, 6.6842, 6.9474, 7.2105, 7.4737,
         7.7368, 8.0000]])

In [70]:
# Create a tensor filled with 0's
torch.zeros(3, 5)

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])

In [73]:
# Create a tensor filled with 1's
t = torch.ones(3, 2, 5)
t

tensor([[[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]]])

In [74]:
# Create a tensor with the diagonal filled with 1
torch.eye(3)

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

## Casting

In [76]:
# Helper to get what kind of tensor types
torch.*Tensor?

In [77]:
m

tensor([[2., 5., 3., 7.],
        [4., 2., 1., 9.]])

In [78]:
# This is basically a 64 bit float tensor
m_double = m.double()
m_double

tensor([[2., 5., 3., 7.],
        [4., 2., 1., 9.]], dtype=torch.float64)

In [79]:
# This creates a tensor of type int8
m_byte = m.byte()
m_byte

tensor([[2, 5, 3, 7],
        [4, 2, 1, 9]], dtype=torch.uint8)

In [80]:
# Move your tensor to GPU device 0 if there is one (first GPU in the system)
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
m.to(device)

tensor([[2., 5., 3., 7.],
        [4., 2., 1., 9.]])

In [81]:
# Converts tensor to numpy array
m_np = m.numpy()
m_np

array([[2., 5., 3., 7.],
       [4., 2., 1., 9.]], dtype=float32)

In [ ]:
# In-place fill of column 0 and row 0 with value -1
m_np[0, 0] = -1
m_np

In [ ]:
m

In [82]:
# Create a tensor of integers ranging from 0 to 4
import numpy as np
n_np = np.arange(5)
n = torch.from_numpy(n_np)
print(n_np, n)

[0 1 2 3 4] tensor([0, 1, 2, 3, 4])


In [83]:
# In-place multiplication of all elements by 2 for tensor n
# Because n is essentially n_np, not a clone, this affects n_np
n.mul_(2)
n_np

array([0, 2, 4, 6, 8])

## More fun

In [58]:
# Creates two tensors of size 1x4
a = torch.Tensor([[1, 2, 3, 4]])
b = torch.Tensor([[5, 6, 7, 8]])
print(a.size(), b)

torch.Size([1, 4]) tensor([[5., 6., 7., 8.]])


In [59]:
# Concatenate on axis 0, so you get 2x4
torch.cat((a, b), 0)

tensor([[1., 2., 3., 4.],
        [5., 6., 7., 8.]])

In [60]:
# Concatenate on axis 1, so you get 1x8
torch.cat((a, b), 1)

tensor([[1., 2., 3., 4., 5., 6., 7., 8.]])